import { DurableObject } from 'cloudflare:workers';
import type { JobQueueDurableObject, UploadSessionDurableObject } from '../index';

export type AppEnv = Env & {
	JOB_QUEUE: DurableObjectNamespace<JobQueueDurableObject>;
	FILE_UPLOADS: DurableObjectNamespace<UploadSessionDurableObject>;
	WEBHOOK_SECRET?: string;
	QUEUE_API_TOKEN?: string;
	GITHUB_APP_PRIVATE_KEY_PEM?: string;
	GITHUB_ALLOWED_REPOS?: string;
	GITHUB_ALLOWED_WORKFLOWS?: string;
	GITHUB_ALLOWED_WORKFLOWS_BY_REPO?: string;
	AGENT_BRANCH_PREFIX?: string;
	DEFAULT_BASE_BRANCH?: string;
	DEFAULT_AUTO_IMPROVE_MAX_CYCLES?: string;
	REQUIRE_WEBHOOK_SECRET?: string;
	GITHUB_API_URL?: string;
	GITHUB_APP_ID?: string;
	GITHUB_APP_INSTALLATION_ID?: string;
	MIRROR_GITHUB_APP_ID?: string;
	MIRROR_GITHUB_APP_INSTALLATION_ID?: string;
	MIRROR_GITHUB_APP_PRIVATE_KEY_PEM?: string;
	WORKING_STALE_AFTER_MS?: string;
	REVIEW_STALE_AFTER_MS?: string;
	DISPATCH_DEDUPE_WINDOW_MS?: string;
	AUDIT_RETENTION_COUNT?: string;
	DELIVERY_RETENTION_COUNT?: string;
	CLOUDFLARE_API_TOKEN?: string;
	CLOUDFLARE_ACCOUNT_ID?: string;
	CLOUDFLARE_WORKER_SCRIPT_NAME?: string;
	SELF_REPO_KEY?: string;
	SELF_DEPLOY_WORKFLOW?: string;
	SELF_LIVE_URL?: string;
	SELF_MIRROR_URL?: string;
	SELF_CURRENT_URL?: string;
	SELF_DEPLOY_ENV?: string;
	SELF_RELEASE_COMMIT_SHA?: string;
	SELF_DEFAULT_DEPLOY_TARGET?: string;
	SELF_REQUIRE_MIRROR_FOR_LIVE?: string;
	MCP_REQUIRE_ACCESS_AUTH?: string;
	MCP_ALLOWED_EMAILS?: string;
	MCP_ALLOWED_EMAIL_DOMAINS?: string;
	CHATGPT_MCP_AUTH_MODE?: string;
	CHATGPT_MCP_ISSUER?: string;
	CHATGPT_MCP_AUDIENCE?: string;
	CHATGPT_MCP_JWKS_URL?: string;
	CHATGPT_MCP_JWKS_JSON?: string;
	CHATGPT_MCP_ALLOWED_EMAILS?: string;
	GUI_OIDC_CLIENT_ID?: string;
	GUI_OIDC_AUDIENCE?: string;
	GUI_OIDC_SCOPE?: string;
};

export { DurableObject };
